pipeline {
    agent any
    environment {
        
        reg_address = "421320058418.dkr.ecr.ap-south-1.amazonaws.com"
        repo = "robot-shop-ashutosh"
        
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Ashutosh-aws/robot-shop.git'
                }
        }
        
        stage('build docker'){
            steps{
          
                sh  'docker build -t catalogue/robot-shop catalogue/'
                sh 'docker tag catalogue/robot-shop ${reg_address}/${repo}:catalogue-build'
                 }
        }
        stage('ECR logging'){
                steps{
                 sh 'aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 421320058418.dkr.ecr.ap-south-1.amazonaws.com'
                  }
        }
        
        stage('docker push'){
                 steps{
                     sh 'docker push ${reg_address}/${repo}:catalogue-build'
            
                    }
        }
    }
}

